househol_power_comp<-subset(read.table("household_power_consumption.txt",header=T,sep=";",na.string="?"),Date %in% c("2/2/2007","1/2/2007"))
househol_power_comp$Date<-as.Date(househol_power_comp$Date,"%d/%m/%Y")
househol_power_comp$Time<-strptime(paste(househol_power_comp$Date,househol_power_comp$Time),"%Y-%m-%d %H:%M:%S")
png(filename="plot3.png")
with(househol_power_comp,plot(Time,Sub_metering_1,main="",type="n",ylab="Energy sub metering",xlab=""))
with(househol_power_comp,lines(Time,Sub_metering_1))
with(househol_power_comp,lines(Time,Sub_metering_2,col="red"))
with(househol_power_comp,lines(Time,Sub_metering_3,col="blue"))
legend("topright",cex=0.7,lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()